<?php

namespace app\controllers;

use Yii;
use app\models\Counter;
use app\models\CounterSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


class LangController extends Controller
{
    public function beforeAction($action)
    {
        $lang = Yii::$app->user->isGuest? 'ru' : $usr = Yii::$app->user->identity->lang;
        Yii::$app->language = $lang;


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
