<?php

namespace app\controllers;

use Yii;
use app\models\Counter;
use app\models\CounterSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


class LangController extends Controller
{
    public function beforeAction($action)
    {
        $session = Yii::$app->session;
        $lang = isset($_SESSION['lang']) ? $_SESSION['lang'] : 'ru';
        if (Yii::$app->user->isGuest){
        }else {
            $lang = isset($_SESSION['lang']) ? $_SESSION['lang'] : Yii::$app->user->identity->lang;
        }

        Yii::$app->language = $lang;


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
